### ISSUE TITLE
Feature request: conversion history

### ISSUE THREAD

**Issue by whitequark** [tiffany352/rink-rs#10]
I find it rather common that I write some complicated expression, quit rink, and then want to run a slightly modified form of it the next time. I would hugely appreciate a persistent history.

**Comment by tiffany352** [comment]
I've added it, but it will lose history if you have multiple rink sessions running at the same time, and there isn't really enough API in linefeed exposed to fix that, afaik. There may also be some bugs, I haven't tested it thoroughly.

**Comment by whitequark** [comment]
I'm fine with that; it's not your responsibility to fix readline, and this is how bash and co behave anyway.
