### ISSUE TITLE
Provide access to result of previous calculation

### ISSUE THREAD

**Issue by leftshift** [tiffany352/rink-rs#104]
Sometimes, I like to immediately reuse the result of an operation in my next calculation. This feature is available as `ANS` in some regular standalone calculators.

In a way, this is also available in the python shell: `_` (underscore) is always bound to the result of the result of the previous expression. I think this might be a good candidate for rink too, as it's easy to type and is easy to tell apart from units.

Of course, in a way this opens the can of worms of supporting variables, as the evaluation logic needs to be able to resolve what `_` is. It also raises the question whether some kind of generalized support for assigning and using variables might make sense, but that might also be out of scope for rink.

What are your thoughts on this? I don't have a lot of experience with rust but I'd be interested in having a look at this.

**Comment by tiffany352** [comment]
It's definitely something I'd like to add, I just haven't gotten around to it yet.

It should be possible by adding a new field to Context to keep track of the last expression result and returning that when looking up a variable named `_` with a high precedence. For variables, using a map and adding some new syntax, probably `let foo = expr`.
