### ISSUE TITLE
Build / Installation problems

### ISSUE THREAD

**Issue by urabenstein** [tiffany352/rink-rs#14]
I've just discovered this repository and wanted to try it, but I'm not able to build the project. I've tried "cargo install rink", cloning the repo and using "cargo build" and adding it as a dependency to one of my own projects. For every method, there's the following error

running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/home/user/rink-rs/target/debug/build/openssl-5464f8f6e728c35a/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c:1:25: fatal error: openssl/ssl.h: No such file or directory
cargo:warning=compilation terminated.
ExitStatus(ExitStatus(256))

I've tried using rustc 1.14.0 as well as 1.16.0-nightly on Ubuntu 16.04. 

Do you have any hints for me?

**Comment by tiffany352** [comment]
There are some native dependencies like openssl and gmp which must be installed that I forgot to mention in the readme.

**Comment by urabenstein** [comment]
I've openssl (version 1.0.2g) and libgmp10 installed. Doesn't change anything.

**Comment by whitequark** [comment]
@urabenstein I *think* you need openssl 1.1? Not sure though

**Comment by urabenstein** [comment]
That did solve it! Thank you very much!
