### ISSUE TITLE
trigonometric functions have confusing unit behavior

### ISSUE THREAD

**Issue by xeniarose** [tiffany352/rink-rs#148]
The following in eval.rs clones the input units for all trig functions

<https://github.com/tiffany352/rink-rs/blob/4a492c64f33f51a89a685d31365042d21cb4f0ed/core/src/runtime/eval.rs#L289-L348>

this results in some confusing behavior when running trig functions with units

```
> sin(10 deg)
approx. 173.6481 milliradian (angle)
> atan2(5 ft, 2 ft)
approx. 1.190289 meter (length)
```

i think that the following behavior would make more sense:

- `sin`, `cos`, and `tan` should require either dimensionless or angle units as input, and provide a dimensionless output
- `asin`, `acos`, `atan`, should require dimensionless input and provide angle output
- `atan2` should provide angle output, and retain its current check for the dimensionality of the two inputs being the same

if you think input unit constraints would be too much, implementing just the output unit changes would also be fine. i can make a PR for this if these changes are wanted

**Comment by tiffany352** [comment]
Sorry it took so long to get around to this. I agree, this is a much better way to handle the units on these functions.
