### ISSUE TITLE
"digits" doesn't work

### ISSUE THREAD

**Issue by jonas-schievink** [tiffany352/rink-rs#18]
The wiki lists a few examples for usage of the `digits` modifier:

```
> 2^128 -> digits
340282366920938463463374607431768211456 (dimensionless)
> 1/7 -> digits 50
1/7, approx. 0.1428571428571428571428571428571428571428571428571428 (dimensionless)
> googol -> digits
10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 (dimensionless)
```

However, all of them fail with "No such unit digits" when used on the current master.

**Comment by tiffany352** [comment]
I'm not able to reproduce this. Are you sure you're using up to date code?

**Comment by jonas-schievink** [comment]
Sorry, I was using the current crates.io version, not master. Will check again with master later.

**Comment by jonas-schievink** [comment]
Ah, of course, the last release was before `digits` was added, my bad.
