### ISSUE TITLE
Rink 0.4.1 has runtime errors

### ISSUE THREAD

**Issue by coder543** [tiffany352/rink-rs#21]
After removing rink 0.4.0, I installed rink 0.4.1 with "cargo install rink", and now I get thousands of lines of error messages when I run rink. :/ This happens under Ubuntu natively, and it happens under Windows on Bash for Windows with that version of Ubuntu too. I've attached an output.txt file containing all of the output.

[output.txt](https://github.com/tiffany352/rink-rs/files/1033857/output.txt)

**Comment by polyzen** [comment]
Fairly unfamiliar with cargo, but `cargo build --release` worked for me.

**Comment by coder543** [comment]
`cargo install rink` just downloads the rink package from crates.io, then runs `cargo build --release` and saves a link to the binary somewhere in your $PATH, basically. I'm not sure what's going wrong, but I've reproduced this on more than one machine, so I'm reporting it here.

**Comment by coder543** [comment]
It was working fine on 0.4.0, but something about 0.4.1 must be different. I'm still a huge fan of rink, just trying to get this kink worked out!

**Comment by tiffany352** [comment]
There could be something wrong with the way it embeds the definitions file into the binary, I'm not sure what though. Do you have an out of date or malformed file named "definitions.units" in your current directory or ~/.config/rink?

**Comment by tiffany352** [comment]
I kind of hacked together the parser as quickly as possible so these error messages are kind of so terrible I can't tell what's going wrong..

**Comment by whitequark** [comment]
I can confirm rink 0.4.1 is broken, and removing `~/.config/rink` does nothing to fix it

**Comment by polyzen** [comment]
FWIW, this worked for me: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rink

**Comment by coder543** [comment]
Sorry for taking so long to respond. I am pretty sure I tested `cargo install rink` on one fresh Linux VM, and it had the same result.

If I can find time soon, I'll try to actually figure out what's going on.

**Comment by coder543** [comment]
Using `cargo clone rink`, it's easy to download the artifact that `cargo` uses for `cargo install rink`.

I have attached [the artifact here](https://github.com/tiffany352/rink-rs/files/1042382/rink.zip)
. I had to comment out the workspace in the toml file, because it was complaining, but this artifact appears to contain unit definition files that are different than what is currently in the git repo.

I'm not sure how this happened in this specific case, but this likely means that at the time `cargo publish` was run, an out-of-date version of the unit definition files happened to be in the crate folder?

So, it is an issue with the unit files, but it isn't specific to any one user's computer. I think the crate just needs to be republished, and hopefully the right files will be uploaded.

You can download the zip file I attached up above, and you can build it and run it yourself and see the error messages.

**Comment by coder543** [comment]
@polyzen that's AUR script is building directly from the Git repo, which has the correct unit files. For many Rust developers like myself, it's logical to use `cargo` to install and manage tools written in Rust, plus I'm not using an Arch distro at the moment for my daily work.

**Comment by tiffany352** [comment]
I've figured out the problem, I think.. I published from windows, and git converted definitions.units to CRLF, and rink's parser barfs on CRLFs...

**Comment by tiffany352** [comment]
I've published 0.4.2 which includes support for CRLF (instead of finding a way to publish LFs from windows... Don't have a linux machine setup at the moment.)

**Comment by whitequark** [comment]
I can confirm this works on Linux.
