### ISSUE TITLE
Doc-tests currently failing

### ISSUE THREAD

**Issue by polyzen** [tiffany352/rink-rs#23]
Output of `RUST_BACKTRACE=1 cargo test --release --doc`: https://ptpb.pw/b9hk

FWIW, also tested with #22 applied.

Edit: Arch Linux, Rust 1.19.0, Cargo 0.20.0

**Comment by tiffany352** [comment]
I'm pretty sure this is a bug in rustc - I have been able to reproduce the issue only inconsistently, and the error message seems totally unrelated to any of the doc tests.

**Comment by polyzen** [comment]
Currently passing.
