### ISSUE TITLE
Updated units database

### ISSUE THREAD

**Issue by ormung** [tiffany352/rink-rs#25]
"definition.units" has been updated in latest gnu units (v2.16 of the file, but found inside v2.14 of the source code)

**Comment by tiffany352** [comment]
Changes in the file:

- The addition of <number>score units, such as "fourscore"
- A few new wine measurements
- Nuclear weapon yields
- IP address space calculations
- Some more gauge size tables that Rink doesn't support
- Cleaned up whitespace

Some of these make sense to add, but the file has been modified substantially so it isn't as easy as just applying a patch.

**Comment by ormung** [comment]
I understand, I thought it was taken as is
