### ISSUE TITLE
% interacts weirdly with **

### ISSUE THREAD

**Issue by whitequark** [tiffany352/rink-rs#26]
E.g.:
```
> (100.0860%) ** 365
approx. 1.368568 (dimensionless)
> 100.0860% ** 365
1.00086e-728 (dimensionless)
```

**Comment by tiffany352** [comment]
The AST looks like this currently:
```
(Pow
  (Juxtapose
    (Number 100.0860)
    (Unit "%"))
  365)
```
The % unit could be turned into a suffix operator (it would still need to parse as a valid unit though, because `-> %`).

**Comment by whitequark** [comment]
Yeah. Any guidance?

**Comment by tiffany352** [comment]
I'd make % a token and handle it in two places, I think:

- In `parse_term`, parse it as Unit("%")
- In `parse_pow`, parse LHS and then peek for a % token, if it finds one then return Mul(left, Unit("%"))

I'll try working on this tonight.

**Comment by tiffany352** [comment]
This should be fixed in latest master. Hopefully this doesn't create any new unintuitive edge cases.

**Comment by whitequark** [comment]
Thanks!
