### ISSUE TITLE
Please consider committing Cargo.lock

### ISSUE THREAD

**Issue by polyzen** [tiffany352/rink-rs#35]
`error: the lock file needs to be updated but --locked was passed to prevent this`

**Comment by polyzen** [comment]
Looks like this would also be needed:
https://github.com/rust-lang/cargo/issues/5654

**Comment by tiffany352** [comment]
This will make it so that the CLI you install from crates.io won't fail to build when a dependency updates? I haven't been keeping up with this, I'm not quite sure why this requires a special cargo feature flag to be enabled.

**Comment by polyzen** [comment]
Exactly, for reproducible builds. 

This gives people the ability to commit their lock files and ship them with binary crates, avoiding:
https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by polyzen** [comment]
I've learned unstable Cargo features require Cargo nightly. Will bump this once it's stabilized.

**Comment by polyzen** [comment]
> [Cargo will be changed to always include Cargo.lock in the .crate file if the package has binaries or examples.](https://github.com/rust-lang/cargo/issues/5654#issuecomment-497863987)
