### ISSUE TITLE
Create new version for crates.io

### ISSUE THREAD

**Issue by danielschemmel** [tiffany352/rink-rs#38]
For some time now, the version of rink on crates.io has been failing to build on many of my machines due to a problem with OpenSSL. However, I just noticed that master builds fine on my machines (possibly due to 0db3f4dcd0e7b661c720418bedd88f9e4e6e37b7).

It would be much appreciated if a new version would be pushed to crates.io, so that I can delete the debian stable docker container I currently use for rink ;).

**Comment by tiffany352** [comment]
Done!

https://github.com/tiffany352/rink-rs/releases/tag/v0.4.4
