### ISSUE TITLE
Openssl dependency fails to install

### ISSUE THREAD

**Issue by cipharius** [tiffany352/rink-rs#39]
If system has OpenSSL v1.0+, dependancy `openssl v0.9.24` fails to install. Searching around reveals that `openssl v0.10+` fixes this incompatibility.

If I add `openssl = "^0.10"` to rink `Cargo.toml`, it installs without issues.

Didn't create a pull request as I'm not familiar with rust and not sure if this is a valid solution.

**Comment by polyzen** [comment]
https://github.com/tiffany352/rink-rs/issues/38

**Comment by cipharius** [comment]
Leaving this issue still open, as the problem is that `cargo install rink` doesn't work out of the box. Personally I managed to get rink working, just wanted to open this issue as reference for others.

**Comment by polyzen** [comment]
The Rink crate is at `0.4.4`, so it should work.

**Comment by cipharius** [comment]
Attempted installing rink with cargo again and today it worked fine. Probably cargo was out of date the first time I tried getting rink.
