### ISSUE TITLE
Add support for number base conversions

### ISSUE THREAD

**Issue by whitequark** [tiffany352/rink-rs#4]
E.g.:
```
You have: 0x1b1e48
You want: 
        Definition: 1777224
```
and probably the other way too (no idea how to do it in GNU units)

**Comment by tiffany352** [comment]
Should already be supported, unless you mean something else.

```
> 0xfff
4095 (dimensionless)
> 0b1110011
115 (dimensionless)
> 12345 -> hex
3039 (dimensionless)
> pi -> bin
approx. 11.00100 (dimensionless)
> 45678 -> base 26
2fem (dimensionless)
```

**Comment by whitequark** [comment]
Hmm, that's not in rink 0.3.2... needs a cargo push?

**Comment by whitequark** [comment]
Ah right `cargo install --git https://github.com/tiffany352/rink-rs rink -f` works, thanks!
