### ISSUE TITLE
Suggestion for improving the UX of the web interface

### ISSUE THREAD

**Issue by ctsrc** [tiffany352/rink-rs#48]
When someone opens the web interface of Rink they see this:

![Screenshot of Rink web app](https://user-images.githubusercontent.com/36199671/69835401-a34b0b80-1241-11ea-9deb-b2cfa2e5729f.png)

The input field on that page feels more like a small site-search box that you would use for looking up documentation or similar information than a natural main point of attention and interaction.

For example, compare that to the search boxes on GitHub, crates.io and a whole slew of other websites, where the search box is secondary to what is the main focus of the page you are on.

![Screenshot of GitHub](https://user-images.githubusercontent.com/36199671/69835418-d097b980-1241-11ea-9c95-e37608850c62.png)

![Screenshot of crates.io](https://user-images.githubusercontent.com/36199671/69835426-dee5d580-1241-11ea-9e34-7f65b164c842.png)

And then look at sites like SymPy Gamma and Wolfram|Alpha, where the input box is meant to be the main focus of the page you are on.

![Screenshot of SymPy Gamma](https://user-images.githubusercontent.com/36199671/69835458-253b3480-1242-11ea-81d2-84ed09c84bfd.png)

![Screenshot of Wolfram|Alpha](https://user-images.githubusercontent.com/36199671/69835476-41d76c80-1242-11ea-9ad6-f7dbc1cf8689.png)

In my opinion, the user experience of the Rink web interface would improve a lot if it drew inspiration from these two (which in turn basically follow the model of Google and other search engines).

Have a big input field with an "=" button next to it that becomes the main focus of the user when they open the web interface.

**Comment by tiffany352** [comment]
Yeah, those are good suggestions. I'd like to improve the web interface soon but it's difficult to get motivation to work on rink.

**Comment by ctsrc** [comment]
> I'd like to improve the web interface soon but it's difficult to get motivation to work on rink.

Understandable, I have it the same way too sometimes with some of my own personal projects.
