### ISSUE TITLE
Calculations with properties don't seem to compose

### ISSUE THREAD

**Issue by whitequark** [tiffany352/rink-rs#6]
Ex.:
![2651](https://cloud.githubusercontent.com/assets/54771/19414095/ed45082c-9331-11e6-8f7d-2b3544b0aaca.png)

![2650](https://cloud.githubusercontent.com/assets/54771/19414089/dc7879c0-9331-11e6-82b1-2ac8a4288cae.png)

**Comment by tiffany352** [comment]
It's an issue with the precedence of the `of` operator. The way it works now, it's reading as `(density) of (milk * 10L)`. I think the only way to fix this is to finally give in and make parsing dependent on the data file, which would allow me to stop parsing `of` at the first substance. For now, I've found myself writing expressions backwards instead, e.g. `10L * density of milk`. Idiomatically, this expression should probably be written `mass of 10L milk`, which does work.

**Comment by whitequark** [comment]
Aside from all above, I think the error message should be fixed also.

**Comment by tiffany352** [comment]
Yeah, it should indicate that the property exists but is not useful or potentially misleading in context.
