### ISSUE TITLE
Code coverage is not being updated

### ISSUE THREAD

**Issue by mkroman** [tiffany352/rink-rs#60]
This is just a heads up that [kcov is not being run in CI](https://travis-ci.org/github/tiffany352/rink-rs/jobs/709562612#L673)

I used your repo as a template when adding code coverage to my own tests and ended up with https://github.com/mkroman/webalert/commit/77ce8b4b32883fdb0f0c5b1343a566c1f1cc8b6b as I had several issues with your old approach - the biggest one being that when my crate is a lib, it doesn't seem to just dump the tests in `target/debug/<test>`, but instead dumped it as executables in `target/debug/deps/…` along with the built crate bins.

This created a new problem - I couldn't distinguish between tests and the CLI bin, and `kcov` would run and show code coverage for the failure path of my CLI despite it being untested.

That's when I found [cargo-kcov](https://github.com/kennytm/cargo-kcov) which parses the output of `cargo test` to distinguish tests from crate bins and then runs them. But unfortunately it seems a lot slower to run than it should be.

**Comment by tiffany352** [comment]
Took a while, but I finally got this working again in #175. I switched to [cargo llvm-cov](https://github.com/taiki-e/cargo-llvm-cov).
