### ISSUE TITLE
Error in rink web

### ISSUE THREAD

**Issue by alexalemi** [tiffany352/rink-rs#74]
The web app doesn't seem to handling it's decades correctly.

For instance `2 pi radius of earth / c` returns 133 seconds instead of 133 milliseconds, despite both the radius of earth and speed of light being correct. This does work in the CLI.

**Comment by tiffany352** [comment]
That's a pretty bad issue, I'll take a look soon.

**Comment by tiffany352** [comment]
Should be fixed now, you might have to hard reload the page because of the service worker caching files.
![image](https://user-images.githubusercontent.com/1254344/93721192-0c8a6b00-fb43-11ea-83e6-fcc823a84bec.png)
