### ISSUE TITLE
eV are used for energy but also mass

### ISSUE THREAD

**Issue by Kezii** [tiffany352/rink-rs#97]

**Comment by tiffany352** [comment]
You can get the mass version with `eV / c^2`. Rink doesn't support overloading or inferring which unit you meant, it requires to explicitly disambiguate e.g. `oz` vs `floz`.

I could add a mass version of eV under a different name though, if there's a common shorthand for it.

**Comment by Kezii** [comment]
fair enough, I don't think there's a common name for eV as mass, even though they are commonly used with "MeV" or "GeV" for mass
